# Generated by Django 3.1 on 2020-10-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ODE_finder', '0002_experiment_simulationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationresult',
            name='signal_preprocessor',
            field=models.CharField(choices=[('GP', 'Gaussian Process'), ('SP', 'Spline')], default='SP', max_length=2),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='title',
            field=models.CharField(default='Simulation_result', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
