# Generated by Django 3.1 on 2020-10-12 14:03

import ODE_finder.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ODE_finder', '0003_auto_20201005_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='csv_file',
            field=models.FileField(upload_to='experiments/', validators=[ODE_finder.validators.validate_csv_extension]),
        ),
    ]
